TreinTickets/TreinTickets/Models/ErrorViewModel.cs
namespace TreinTickets.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TreinTickets/TreinTickets/ViewModels/BestellingVM.cs
using TreinTickets.Models.Entities;

namespace TreinTickets.ViewModels
{
    public class BestellingVM
    {
        public double TotaalBedrag { get; set; }
        public Tickets Ticket { get; set; }
        public string Status { get; set; }

    }
}

TreinTickets/TreinTickets/ViewModels/ReisCreateVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using TreinTickets.Models.Entities;

namespace TreinTickets.ViewModels
{
    public class ReisCreateVM
    {
        
        [Required]
        [Display(Name = "Class")]
        public int TreinKlasseId { get; set; }
        public IEnumerable<SelectListItem>? TreinKlasses { get; set; }

        
        [Required]
        [Display(Name = "From")]
        public int VertrekStadId { get; set; }
        public IEnumerable<SelectListItem>? Vertreksteden { get; set; }

        
        [Required]
        [Display(Name = "To")]
        public int BestemmingsStadId { get; set; }
        public IEnumerable<SelectListItem>? Bestemmingssteden { get; set; }

        
        [Required]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-ddTHH:mm}")]
        [DateCheck]
        [Display(Name = "Departure")]
        public DateTime VertrekDag { get; set; }


        public class DateCheck : ValidationAttribute
        {
            protected override ValidationResult? IsValid(object? value, ValidationContext validationContext)
            {
                DateTime vertrekdag = (DateTime)value;
                TimeSpan difference = vertrekdag.Date - DateTime.Today;
                if (difference < TimeSpan.Zero || difference > TimeSpan.FromDays(14))
                {
                    return new ValidationResult("U kunt maar 14 dagen op voorhand boeken");
                }
                return ValidationResult.Success;
            }
        }
    }
}

TreinTickets/TreinTickets/ViewModels/RitVM.cs
using System.ComponentModel.DataAnnotations;
using TreinTickets.Models.Entities;

namespace TreinTickets.ViewModels
{
    public class RitVM
    {
        public string? TreinKlasse { get; set; }

        public int PlaatsNummer { get; set; }

        public string? VertrekStad { get; set; }

        public string? BestemmingsStad { get; set; }

        public DateTime VertrekDag { get; set; }
    }
}

TreinTickets/TreinTickets/ViewModels/StadVM.cs
namespace TreinTickets.ViewModels
{
    public class StadVM
    {
        public string StadNaam { get; set; }
    }
}

TreinTickets/TreinTickets/ViewModels/TicketsVM.cs
using TreinTickets.Models.Entities;

namespace TreinTickets.ViewModels
{
    public class TicketsVM
    {
        public Rit Rit { get; set; }
    }
}

TreinTickets/TreinTickets/ViewModels/TreinVM.cs
using TreinTickets.Models.Entities;

namespace TreinTickets.ViewModels
{
    public class TreinVM
    {
        public int Id { get; set; }
        public int VertrekStadId { get; set; }
        public int BestemmingsStadId { get; set; }
        public int AantalZitplaatsen { get; set; }
    }
}

TreinTickets/TreinTickets/Controllers/HomeController.cs
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Localization;

using TreinTickets.Models.Data;
using TreinTickets.Models.Entities;

namespace TreinTickets.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IStringLocalizer<HomeController> _localizer;
        private readonly TreinTicketsDbContext _context;

        public HomeController(ILogger<HomeController> logger, IStringLocalizer<HomeController> localizer, TreinTicketsDbContext context)
        {
            _logger = logger;
            _localizer = localizer;
            _context = context; 
        }

        public IActionResult Index()//home pagina
        {
            return View();
        }

        public IActionResult Info()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SetAppLanguage(string lang, string returnUrl)
        {
            // er wordt een cookie aangemaakt met de naam .AspNetCore.Culture (zie browser cookie)
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(lang)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );
            return LocalRedirect(returnUrl);
        }
    }
}

TreinTickets/TreinTickets/Controllers/ReisController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Diagnostics;
using TreinTickets.Models;
using TreinTickets.Models.Data;
using TreinTickets.Models.Entities;
using TreinTickets.Services.Interfaces;
using TreinTickets.ViewModels;
using Microsoft.EntityFrameworkCore;

namespace TreinTickets.Controllers
{
    public class ReisController : Controller
    {
        private TreinTicketsDbContext _context;
        private IService<Stad> _stadService;
        private IService<Rit> _ritService;
        private IService<TreinKlasse> _klasseService;

        private readonly IMapper _mapper;


        public ReisController(TreinTicketsDbContext context, IService<Stad> stadService, 
            IService<Rit> ritService, IService<TreinKlasse> klasseService, 
            IMapper mapper)
        {
            _context = context;
            _stadService = stadService;
            _ritService = ritService;
            _klasseService = klasseService;
            _mapper = mapper;
            
        }

        public async Task<IActionResult> Search()//invullen form
        {
            var reisCreate = new ReisCreateVM()
            {
                Vertreksteden = new SelectList(await _stadService.GetAll()
                , "Id", "Naam"),
                Bestemmingssteden = new SelectList(await _stadService.GetAll()
                , "Id", "Naam"),
                TreinKlasses = new SelectList(await _klasseService.GetAll()
                , "Id", "Type"),

                VertrekDag = DateTime.Now
            };

            return View(reisCreate);
        }

        public async Task<IActionResult> Ritten()
        {
            var ritten = await _ritService.GetAll();
            List<RitVM> listVM = _mapper.Map<List<RitVM>>(ritten);
            return View(listVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Search(ReisCreateVM reisModel)
        {
            if (ModelState.IsValid)
            {
                var treinen = _context.Treinen.ToList();
                if (treinen.Count > 0)
                {
                    return View("TreinList", treinen);
                }
                else
                {
                    ModelState.AddModelError("", "No trains found that match the search criteria");
                }
            }
            reisModel.Vertreksteden = new SelectList(_context.Steden, "Id", "Naam", reisModel.VertrekStadId);
            reisModel.Bestemmingssteden = new SelectList(_context.Steden, "Id", "Naam", reisModel.BestemmingsStadId);
            return View(reisModel);
        }
    }
}

TreinTickets/TreinTickets/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@*The IViewLocalizer service provides localized strings for a view. The ViewLocalizer class implements this interface and finds the resource location from the view file path.*@
@inject IViewLocalizer Localizer

<div class="wrapper">
    <div class="column1">
        <img src="~/img/treinspoor.jpg" alt="treinspoor" class="ImgSpoor"/>
    </div>
    <div class="column2">
        <div class="text-center">
            <h1 class="Title">@Localizer["Welcome"].Value</h1>
        </div>
        <div class="IconBox">
            <a class="nav-link text-dark" asp-area="" asp-controller="Reis" asp-action="Search">
                <img src=~/img/TreinIcon.png class="Icon" alt="Trein boeken"/>
                <span class="IconText">@Localizer["Book"].Value</span>
            </a>
        </div>
        <div class="IconBox">
            <a class="nav-link text-dark" asp-area="" asp-controller="" asp-action="">
                <img src=~/img/shoppingcart.png class="Icon" alt="Bestellingen bekijken"/>
                <span class="IconText">@Localizer["Orders"].Value</span>
            </a>
        </div>
        <div class="IconBox">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Info">
                <img src=~/img/InfoIcon.png class="Icon" alt="info over site"/>
                <span class="IconText">@Localizer["Info"].Value</span>
            </a>
        </div>
    </div>
    <div class="column3">
        <img src="~/img/treinspoor.jpg" alt="treinspoor" class="ImgSpoor"/>
    </div>
</div>

TreinTickets/TreinTickets/Views/Home/Info.cshtml
@{
    ViewData["Title"] = "Algemene info";
}

<div class="text-center">
    <h1>@ViewData["Title"]</h1>
    <br />
    <hr />
    <div style="display: inline-block;width: 540px;text-align: initial;font-size: 20px; vertical-align: top">
        <p>Op deze website is het mogelijk om een treinticket te boeken
        tussen 7 verschillende steden.
        Deze steden zijn: Londen, Brussel, Parijs, Amsterdam, Rome, Berlijn en Moskou.
        Er reidt elke dag 1 trein naar elke bestemming.</p>

        <p>De afbeelding hiernaast toont de steden met hun verbindingen</p>

        <p>Voor elke stad zijn er 3 hotels beschikbaar waaruit u eventueel kan kiezen,
        ze hebben elk een verschillende prijsklasse.</p>
    </div>
    <img src="~/img/StedenOpKaartImg.png" style="width: 635px;margin-left: 10px;"/>
</div>

TreinTickets/TreinTickets/Views/Reis/Ritten.cshtml
@model IEnumerable<TreinTickets.ViewModels.RitVM>

@{
    ViewData["Title"] = "Ritten";
}

<h1>Ritten</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TreinKlasse)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlaatsNummer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VertrekStad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BestemmingsStad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VertrekDag)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TreinKlasse)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PlaatsNummer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VertrekStad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BestemmingsStad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VertrekDag)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

TreinTickets/TreinTickets/Views/Reis/Search.cshtml
@model TreinTickets.ViewModels.ReisCreateVM

@{
    ViewData["Title"] = "Search";
}

<div class="container">
    <h1>Reis Boeken</h1>
<br />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Search">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TreinKlasseId" class="control-label"></label>
                <select asp-for="TreinKlasseId" class="form-control" asp-items=@Model.TreinKlasses>
                    <option>Please select a class</option>
                </select>
                <span asp-validation-for="TreinKlasseId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VertrekStadId" class="control-label"></label>
                <select asp-for="VertrekStadId" class="form-control" asp-items=@Model.Vertreksteden>
                    <option>Please select a city</option>
                </select>
                <span asp-validation-for="VertrekStadId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BestemmingsStadId" class="control-label"></label>
                <select asp-for="BestemmingsStadId" class="form-control" asp-items=@Model.Bestemmingssteden>
                    <option>Please select a city</option>
                </select>
                <span asp-validation-for="BestemmingsStadId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VertrekDag" class="control-label"></label>
                <input asp-for="VertrekDag" class="form-control" value="@Model.VertrekDag.ToString("yyyy-MM-ddTHH:mm")"/>
                <span asp-validation-for="VertrekDag" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TreinTickets/TreinTickets/Views/Reis/TreinList.cshtml
@model IEnumerable<TreinTickets.ViewModels.TreinVM>

@{
    ViewData["Title"] = "TreinList";
}

<h1>TreinList</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AantalZitplaatsen)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AantalZitplaatsen)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

TreinTickets/TreinTickets/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TreinTickets</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TreinTickets.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">
                                <img src=~/img/HomeIcon.png alt="Home page" style="width: 50px; height:auto"/>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="" asp-action="">
                                <img src=~/img/shoppingcart.png alt="Bestellingen" style="width: 50px; height:auto"/>
                            </a>
                        </li>
                    </ul>
                    @await Html.PartialAsync("_SelectLanguage")
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="layout">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TreinTickets - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <script>
        
        $(document).ready(() => {

            $(".setLang").on("change", () => {

                $('form').submit();
            })
        })
    </script>
</body>
</html>

TreinTickets/TreinTickets/Views/Shared/_SelectLanguage.cshtml
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options


@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> locOptions

@{
    // Represents the feature that provides the current request's culture information. (zie cookie culture wordt uitgelezen als deze aanwwezig) is)
    var currentRequestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = locOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
    var responseUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" :
        $"~{Context.Request.Path.Value}";
}

<div title="@Localizer["Request the culture provider"]
     @currentRequestCulture?.Provider?.GetType().Name">
    <form id="selectLanguage" asp-controller="Home"
          asp-action="SetAppLanguage" asp-route-returnUrl="@responseUrl"
          method="post" class="form-horizontal" role="form">
        <label asp-for="@currentRequestCulture.RequestCulture.UICulture.Name">
            @Localizer["Select Language"]
        </label>
        <select name="lang" class="setLang"
                asp-for="@currentRequestCulture.RequestCulture.UICulture.Name"
                asp-items="cultureItems">
        </select>
    </form>
</div>